---
- name: Import sources.list APT template
  template:
    src: templates/sources.j2
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
  when:
    ansible_os_family == 'Debian'
    and
    debianBaseRepoURL is defined
    and
    debianBaseRepoURL|length
    and
    ubuntuBaseRepoURL is defined
    and
    ubuntuBaseRepoURL|length
