---
- name: Include install.yml
  include: install.yml

- name: Include create.yml
  include: create.yml
  when:
    repositories['add']['url'] is defined
    and
    repositories['add']['url'] | length > 0

- name: Include base.yml
  include: base.yml
  when: addBaseRepositories == true

- name: Include add.yml
  include: add.yml
  when:
    repositories['add']['url'] is defined
    and
    repositories['add']['url'] | length > 0

- name: Include remove.yml
  include: remove.yml
  when:
    repositories['remove']['url'] is defined
    and 
    repositories['remove']['url'] | length > 0
